[basic]
year_of_birth = 1965
pension_age = 67
life_expectancy = 87
average_house_size_m2 = 67.8
variable_unit_cost_electricity = 0.143
variable_unit_cost_gas = 0.044

[energy_use]
average = 133
passive = 15

[CAGR]
gas = 0.05
electricity = 0.08
